### ISSUE TITLE
Subrange type looks strange

### ISSUE THREAD

**Issue by weldingtorch** [AnsonYeung/vscode-pascal-language-basics#10]
Defining types like
```pascal
type Latin = 'a'..'z';
```
or using them in constructors
```pascal
var setOfDigits: set of 0..9;
```
doesn't highlight range bounds `'a'` and `'z'` as chars nor `1` and `9` as integers:
![image](https://github.com/user-attachments/assets/f3e97a59-7088-4a02-94fb-8a70ba4190f1)

**Comment by AnsonYeung** [comment]
nice catch
